# Generated by Django 5.2.3 on 2025-06-17 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID_типа_оборудования', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Наименование_оборудования', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Тип_оборудования',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRegulation',
            fields=[
                ('id', models.BigIntegerField(db_column='ID_норматива', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Название_норматива', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Норматив_обслуживания',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID_вида_обслуживания', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Наименование_обслуживания', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Вид_обслуживания',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(db_column='ID_роли', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Наименование_роли', max_length=30)),
            ],
            options={
                'db_table': 'Роль',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('inventory_number', models.BigIntegerField(db_column='Инвентарный_номер', primary_key=True, serialize=False)),
                ('commissioning_date', models.DateField(db_column='Дата_ввода')),
                ('name', models.CharField(db_column='Наименование_оборудования', max_length=30)),
                ('equipment_type', models.ForeignKey(blank=True, db_column='ID_типа_оборудования', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.equipmenttype')),
            ],
            options={
                'db_table': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(db_column='Логин', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Пароль', max_length=30)),
                ('first_name', models.CharField(db_column='Имя', max_length=30)),
                ('last_name', models.CharField(db_column='Фамилия', max_length=30)),
                ('middle_name', models.CharField(blank=True, db_column='Отчество', max_length=30, null=True)),
                ('role', models.ForeignKey(blank=True, db_column='ID_роли', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.role')),
            ],
            options={
                'db_table': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_column='Плановая_дата')),
                ('status', models.CharField(db_column='Статус', max_length=30)),
                ('equipment', models.ForeignKey(db_column='Инвентарный_номер', on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.equipment')),
                ('maintenance_type', models.ForeignKey(db_column='ID_вида_обслуживания', on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.maintenancetype')),
            ],
            options={
                'db_table': 'План_обслуживания',
                'unique_together': {('scheduled_date', 'equipment', 'maintenance_type')},
            },
        ),
        migrations.CreateModel(
            name='MaintenancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_months', models.BigIntegerField(db_column='Периодичность')),
                ('regulation', models.ForeignKey(db_column='ID_норматива', on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.maintenanceregulation')),
                ('maintenance_type', models.ForeignKey(db_column='ID_вида_обслуживания', on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.maintenancetype')),
            ],
            options={
                'db_table': 'Периодичность работы',
                'unique_together': {('regulation', 'maintenance_type')},
            },
        ),
    ]
