# Generated by Django 5.2.3 on 2025-06-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='regulation_id',
            field=models.ForeignKey(blank=True, db_column='ID_норматива', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.maintenanceregulation'),
        ),
    ]
